--조인문
SELECT S.SCHEDULE_ID,S.WRITER,S.TITLE,S.CONTENT,
		S.SCHEDULE_DATE ,S.REGDATE, si.ADDRESS 
		FROM SCHEDULES S
		INNER JOIN SCHEDULE_INFO si
		ON S.LOCATION_CODE = si.LOCATION_CODE ;

--INSERT SCHEDULE_INFO 먼저 하고, SCHEDULES INSERT 하기
--SCHEDULE_DATE는 >> input type="datetime-local"
INSERT 
