SELECT S.SCHEDULE_ID,S.WRITER,S.TITLE,S.CONTENT,
		S.SCHEDULE_DATE ,S.REGDATE, si.ADDRESS 
		FROM SCHEDULES S
		INNER JOIN SCHEDULE_INFO si
		ON S.LOCATION_CODE = si.LOCATION_CODE ;
		
	
INSERT INTO SCHEDULE_INFO
	(LOCATION_CODE ,LOCATION_NAME ,ADDRESS ,ADDRESS2 ,PHONE ,LOGUI ,LAT)
	VALUES(SCHEDULE_INFO_SEQ.NEXTVAL,'부천시','주소1','주소2','010-3357-6985',37.566826,126.9786567);

INSERT INTO SCHEDULES
(SCHEDULE_ID, MOZZLE_ID, WRITER, TITLE, CONTENT, SCHEDULE_DATE, REGDATE, DELFLAG, LOCATION_CODE)
VALUES(SCHEDULE_SEQ.NEXTVAL, 1 , '작성자', 'TITLE1', 'CONTENT1', '2021-12-15', SYSDATE, 'N', 1);

CREATE SEQUENCE SCHEDULE_SEQ;

SELECT * FROM SCHEDULE_INFO;
SELECT * FROM SCHEDULES s ;
