  SELECT u.USER_PW, a.AUTH_NAME AUTH
	FROM USERS u INNER JOIN USERS_AUTH a
	ON u.AUTH_CODE = a.AUTH_CODE 
		WHERE u.USER_ID = 'qkrekfthsus';

SELECT * FROM USERS_AUTH ua ;
SELECT * FROM users;

UPDATE USERS SET AUTH_CODE = 2 WHERE USER_ID = 'qkrekfthsus';