SELECT * FROM TEST t ;

INSERT INTO ADMIN.TEST
(ABCD)
VALUES(123);

SELECT sysdate FROM dual;
SELECT CURRENT_TIMESTAMP FROM dual;
ALTER DATABASE SET TIME_ZONE = 'Asia/Seoul';
ALTER SESSION SET TIME_ZONE = 'Asia/Seoul';

ALTER DATABASE SET TIME_ZONE = '+09:00';
ALTER DATABASE G3535C157E1EAF5_MOZZLE 
SET TIME_ZONE='Asia/Seoul';

-- 데이터 초기화
DROP TABLE NOTIFICATION CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE_MEMBER CASCADE CONSTRAINTS;
DROP TABLE SCHEDULES CASCADE CONSTRAINTS;
DROP TABLE USER_MOZZLE CASCADE CONSTRAINTS;
DROP TABLE USERS_AUTH CASCADE CONSTRAINTS;
DROP TABLE MOZZLE_AUTH CASCADE CONSTRAINTS;
DROP TABLE USER_MOZZLE CASCADE CONSTRAINTS;
DROP TABLE MOZZLE CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE MOZZLE_REPORT CASCADE CONSTRAINTS;
DROP TABLE GUEST CASCADE CONSTRAINTS;
DROP TABLE MOZZLE_POST CASCADE CONSTRAINTS;
DROP TABLE POST_REPORT CASCADE CONSTRAINTS;
DROP TABLE BOOKMARK CASCADE CONSTRAINTS;

-- MOZZLE_POST
CREATE TABLE MOZZLE_POST (
	POST_ID   VARCHAR2(20)   NOT NULL, -- POST_ID
	MOZZLE_ID VARCHAR2(20)   NOT NULL, -- MOZZLE_ID
	USER_ID   VARCHAR2(20)   NOT NULL, -- USER_ID
	TITLE     VARCHAR2(200)  NOT NULL, -- TITLE
	CONTENT   VARCHAR2(2000) NULL,     -- CONTENT
	REFER     INTEGER        NOT NULL, -- REFER
	STEP      INTEGER        NOT NULL, -- STEP
	"DEPTH"     INTEGER        NOT NULL, -- DEPTH
	REGDATE   DATE           NOT NULL  -- REGDATE
);

-- MOZZLE_POST
ALTER TABLE MOZZLE_POST
	ADD CONSTRAINT PK_MOZZLE_POST -- MOZZLE_POST 기본키
		PRIMARY KEY (
			POST_ID -- POST_ID
		);

-- USER_MOZZLE
CREATE TABLE USER_MOZZLE (
	USER_ID       VARCHAR2(20)  NOT NULL, -- USER_ID
	MOZZLE_ID     VARCHAR2(20)  NOT NULL, -- MOZZLE_ID
	AUTH_CODE     VARCHAR2(20)  NULL,     -- AUTH_CODE
	NICKNAME      VARCHAR2(50)  NOT NULL, -- NICKNAME
	JOINED_DATE   DATE          NOT NULL, -- JOINED_DATE
	BIRTHDAY_SHOW VARCHAR2(1)   NOT NULL, -- BIRTHDAY_SHOW
	IMAGE_ORIGIN  VARCHAR2(150) NULL,     -- IMAGE_ORIGIN
	IMAGE_SAVED   VARCHAR2(200) NULL      -- IMAGE_SAVED
);

-- USER_MOZZLE
ALTER TABLE USER_MOZZLE
	ADD CONSTRAINT PK_USER_MOZZLE -- USER_MOZZLE 기본키
		PRIMARY KEY (
			USER_ID,   -- USER_ID
			MOZZLE_ID  -- MOZZLE_ID
		);

-- NOTIFICATION
CREATE TABLE NOTIFICATION (
	NOTICE_ID    VARCHAR2(20)   NOT NULL, -- NOTICE_ID
	USER_ID      VARCHAR2(20)   NOT NULL, -- USER_ID
	MOZZLE_ID    INTEGER        NOT NULL, -- MOZZLE_ID
	"TYPE"         VARCHAR2(10)   NOT NULL, -- TYPE
	TITLE        VARCHAR2(200)  NOT NULL, -- TITLE
	CONTENT      VARCHAR2(2000) NOT NULL, -- CONTENT
	NOTICE_TIME  DATE           NOT NULL, -- NOTICE_TIME
	READ_CHECKED VARCHAR2(1)    NOT NULL, -- READ_CHECKED
	DELFLAG      VARCHAR2(1)    NOT NULL  -- DELFLAG
);

-- NOTIFICATION
ALTER TABLE NOTIFICATION
	ADD CONSTRAINT PK_NOTIFICATION -- NOTIFICATION 기본키
		PRIMARY KEY (
			NOTICE_ID, -- NOTICE_ID
			USER_ID    -- USER_ID
		);

-- USERS
CREATE TABLE USERS (
	USER_ID   VARCHAR2(20) NOT NULL, -- USER_ID
	USER_PW   VARCHAR2(20) NOT NULL, -- USER_PW
	USER_NAME VARCHAR2(50) NOT NULL, -- USER_NAME
	AUTH_CODE INTEGER      NOT NULL, -- AUTH_CODE
	BIRTH     DATE         NULL,     -- BIRTH
	EMAIL     VARCHAR2(40) NOT NULL, -- EMAIL
	TEL       VARCHAR2(30) NULL,     -- TEL
	DELFLAG   VARCHAR2(1)  NOT NULL  -- DELFLAG
);

-- USERS
ALTER TABLE USERS
	ADD CONSTRAINT PK_USERS -- USERS 기본키
		PRIMARY KEY (
			USER_ID -- USER_ID
		);

-- MOZZLE_REPORT
CREATE TABLE MOZZLE_REPORT (
	REPORT_ID   VARCHAR2(20)  NOT NULL, -- REPORT_MOZZLE_ID
	MOZZLE_ID   INTEGER       NOT NULL, -- MOZZLE_ID
	REPORT_TIME DATE          NOT NULL, -- REPORT_TIME
	REPORTER    VARCHAR2(20)  NOT NULL, -- REPORTER
	REASON      VARCHAR(2000) NOT NULL  -- REASON
);

-- MOZZLE_REPORT
ALTER TABLE MOZZLE_REPORT
	ADD CONSTRAINT PK_MOZZLE_REPORT -- MOZZLE_REPORT 기본키
		PRIMARY KEY (
			REPORT_ID -- REPORT_MOZZLE_ID
		);

-- SCHEDULES
CREATE TABLE SCHEDULES (
	SCHEDULE_ID   VARCHAR2(20)   NOT NULL, -- SCHEDULE_ID
	MOZZLE_ID     INTEGER        NOT NULL, -- MOZZLE_ID
	WRITER        VARCHAR2(20)   NOT NULL, -- WRITER
	TITLE         VARCHAR2(200)  NOT NULL, -- TITLE
	CONTENT       VARCHAR2(2000) NULL,     -- CONTENT
	SCHEDULE_DATE DATE           NOT NULL, -- SCHEDULE_DATE
	REGDATE       DATE           NOT NULL, -- REGDATE
	DELFLAG       VARCHAR2(1)    NULL,     -- SDELFLAG
	LOCATION_CODE VARCHAR2(20)   NULL      -- LOCATION_CODE
);

-- SCHEDULES
ALTER TABLE SCHEDULES
	ADD CONSTRAINT PK_SCHEDULES -- SCHEDULES 기본키
		PRIMARY KEY (
			SCHEDULE_ID -- SCHEDULE_ID
		);

-- MOZZLE
CREATE TABLE MOZZLE (
	MOZZLE_ID     VARCHAR2(20)   NOT NULL, -- MOZZLE_ID
	MOZZLE_NAME   VARCHAR2(200)  NOT NULL, -- MOZZLE_NAME
	MOZZLE_INTRO  VARCHAR2(2000) NULL,     -- MOZZLE_INTRO
	CREATE_DATE   DATE           NOT NULL, -- CREATE_DATE
	IMAGE_ORIGIN  VARCHAR2(150)  NULL,     -- IMAGE_ORIGIN
	IMAGE_SAVED   VARCHAR2(200)  NULL,     -- IMAGE_SAVED
	CATEGORY_CODE VARCHAR2(2000) NOT NULL, -- CATEGORY_CODE
	STATE         VARCHAR2(1)    NOT NULL, -- STATE
	DELFLAG       VARCHAR2(1)    NOT NULL  -- DELFLAG
);

-- MOZZLE
ALTER TABLE MOZZLE
	ADD CONSTRAINT PK_MOZZLE -- MOZZLE 기본키
		PRIMARY KEY (
			MOZZLE_ID -- MOZZLE_ID
		);

-- POST_REPORT
CREATE TABLE POST_REPORT (
	REPORT_ID   VARCHAR2(20)   NOT NULL, -- REPORT_ID
	POST_ID     VARCHAR2(20)   NOT NULL, -- POST_ID
	REPORT_TIME DATE           NOT NULL, -- REPORT_TIME
	REPORTER    VARCHAR2(20)   NOT NULL, -- REPORTER
	REASON      VARCHAR2(2000) NOT NULL  -- REASON
);

-- POST_REPORT
ALTER TABLE POST_REPORT
	ADD CONSTRAINT PK_POST_REPORT -- POST_REPORT 기본키
		PRIMARY KEY (
			REPORT_ID -- REPORT_ID
		);

-- schedule_member
CREATE TABLE SCHEDULE_MEMBER (
	SCHEDULE_ID VARCHAR2(20) NOT NULL, -- SCHEDULE_ID
	USER_ID     VARCHAR2(20) NOT NULL  -- USER_ID
);

-- schedule_member
ALTER TABLE SCHEDULE_MEMBER
	ADD CONSTRAINT PK_SCHEDULE_MEMBER -- schedule_member 기본키
		PRIMARY KEY (
			SCHEDULE_ID, -- SCHEDULE_ID
			USER_ID      -- USER_ID
		);

-- GUEST
CREATE TABLE GUEST (
	MOZZLE_ID VARCHAR2(20) NOT NULL, -- MOZZLE_ID
	UUID      VARCHAR(200) NOT NULL  -- UUID
);

-- GUEST
ALTER TABLE GUEST
	ADD CONSTRAINT PK_GUEST -- GUEST 기본키
		PRIMARY KEY (
			MOZZLE_ID -- MOZZLE_ID
		);

-- CATEGORY
CREATE TABLE CATEGORY (
	CATEGORY_CODE VARCHAR2(20) NOT NULL, -- CATEGORY_CODE
	CATEGORY_NAME VARCHAR2(50) NOT NULL  -- CATEGORY_NAME
);

-- BOOKMARK
CREATE TABLE BOOKMARK (
	SEQ     VARCHAR2(20) NOT NULL, -- BOOKMARK_ID
	USER_ID VARCHAR2(20) NOT NULL, -- USER_ID
	POST_ID VARCHAR2(20) NOT NULL  -- POST_ID
);

-- BOOKMARK
ALTER TABLE BOOKMARK
	ADD CONSTRAINT PK_BOOKMARK -- BOOKMARK 기본키
		PRIMARY KEY (
			SEQ,     -- BOOKMARK_ID
			USER_ID  -- USER_ID
		);

-- USERS_AUTH
CREATE TABLE USERS_AUTH (
	AUTH_CODE INTEGER      NOT NULL, -- AUTH_CODE
	AUTH_NAME VARCHAR2(50) NOT NULL  -- AUTH_NAME
);

-- USERS_AUTH
ALTER TABLE USERS_AUTH
	ADD CONSTRAINT PK_USERS_AUTH -- USERS_AUTH 기본키
		PRIMARY KEY (
			AUTH_CODE -- AUTH_CODE
		);

-- MOZZLE_AUTH
CREATE TABLE MOZZLE_AUTH (
	AUTH_CODE VARCHAR2(20) NOT NULL, -- AUTH_CODE
	AUTH_NAME VARCHAR2(50) NOT NULL  -- AUTH_NAME
);

-- MOZZLE_AUTH
ALTER TABLE MOZZLE_AUTH
	ADD CONSTRAINT PK_MOZZLE_AUTH -- MOZZLE_AUTH 기본키
		PRIMARY KEY (
			AUTH_CODE -- AUTH_CODE
		);



-- NIFO_LOCATION
CREATE TABLE SCHEDULE_INFO (
	LOCATION_CODE VARCHAR2(20)  NOT NULL, -- LOCATION_CODE
	LOCATION_NAME VARCHAR2(200) NOT NULL, -- LOCATION_NAME
	ADDRESS	      VARCHAR2(255) NOT NULL, -- ADDRESS
	ADDRESS2      VARCHAR2(255) NOT NULL, -- ADDRESS2
	PHONE         VARCHAR2(30)  NOT NULL, -- PHONE
	LOGUI         INTEGER        NOT NULL, -- LOGUI
	LAT           INTEGER        NOT NULL  -- LAT
);

-- NIFO_LOCATION
ALTER TABLE SCHEDULE_INFO
	ADD CONSTRAINT PK_SCHEDULE_INFO -- NIFO_LOCATION 기본키
		PRIMARY KEY (
			LOCATION_CODE -- LOCATION_CODE
		);

-- MOZZLE_POST
ALTER TABLE MOZZLE_POST
	ADD CONSTRAINT FK_MOZZLE_TO_MOZZLE_POST -- MOZZLE -> MOZZLE_POST
		FOREIGN KEY (
			MOZZLE_ID -- MOZZLE_ID
		)
		REFERENCES MOZZLE ( -- MOZZLE
			MOZZLE_ID -- MOZZLE_ID
		);

-- USER_MOZZLE
ALTER TABLE USER_MOZZLE
	ADD CONSTRAINT FK_USERS_TO_USER_MOZZLE -- USERS -> USER_MOZZLE
		FOREIGN KEY (
			USER_ID -- USER_ID
		)
		REFERENCES USERS ( -- USERS
			USER_ID -- USER_ID
		);

-- USER_MOZZLE
ALTER TABLE USER_MOZZLE
	ADD CONSTRAINT FK_MOZZLE_TO_USER_MOZZLE -- MOZZLE -> USER_MOZZLE
		FOREIGN KEY (
			MOZZLE_ID -- MOZZLE_ID
		)
		REFERENCES MOZZLE ( -- MOZZLE
			MOZZLE_ID -- MOZZLE_ID
		);

-- USER_MOZZLE
ALTER TABLE USER_MOZZLE
	ADD CONSTRAINT FK_MOZZLE_AUTH_TO_USER_MOZZLE -- MOZZLE_AUTH -> USER_MOZZLE
		FOREIGN KEY (
			AUTH_CODE -- AUTH_CODE
		)
		REFERENCES MOZZLE_AUTH ( -- MOZZLE_AUTH
			AUTH_CODE -- AUTH_CODE
		);

-- NOTIFICATION
ALTER TABLE NOTIFICATION
	ADD CONSTRAINT FK_USERS_TO_NOTIFICATION -- USERS -> NOTIFICATION
		FOREIGN KEY (
			USER_ID -- USER_ID
		)
		REFERENCES USERS ( -- USERS
			USER_ID -- USER_ID
		);

-- USERS
ALTER TABLE USERS
	ADD CONSTRAINT FK_USERS_AUTH_TO_USERS -- USERS_AUTH -> USERS
		FOREIGN KEY (
			AUTH_CODE -- AUTH_CODE
		)
		REFERENCES USERS_AUTH ( -- USERS_AUTH
			AUTH_CODE -- AUTH_CODE
		);

-- SCHEDULES
ALTER TABLE SCHEDULES
	ADD CONSTRAINT FK_SCHEDULE_INFO_TO_SCHEDULES -- NIFO_LOCATION -> SCHEDULES
		FOREIGN KEY (
			LOCATION_CODE -- LOCATION_CODE
		)
		REFERENCES SCHEDULE_INFO ( -- NIFO_LOCATION
			LOCATION_CODE -- LOCATION_CODE
		);

-- POST_REPORT
ALTER TABLE POST_REPORT
	ADD CONSTRAINT FK_MOZZLE_POST_TO_POST_REPORT -- MOZZLE_POST -> POST_REPORT
		FOREIGN KEY (
			POST_ID -- POST_ID
		)
		REFERENCES MOZZLE_POST ( -- MOZZLE_POST
			POST_ID -- POST_ID
		);

-- schedule_member
ALTER TABLE SCHEDULE_MEMBER
	ADD CONSTRAINT FK_SCHEDULES_TO_SCHDL_MBR -- SCHEDULES -> schedule_member
		FOREIGN KEY (
			SCHEDULE_ID -- SCHEDULE_ID
		)
		REFERENCES SCHEDULES ( -- SCHEDULES
			SCHEDULE_ID -- SCHEDULE_ID
		);

-- schedule_member
ALTER TABLE SCHEDULE_MEMBER
	ADD CONSTRAINT FK_USERS_TO_SCHEDULE_MEMBER -- USERS -> schedule_member
		FOREIGN KEY (
			USER_ID -- USER_ID
		)
		REFERENCES USERS ( -- USERS
			USER_ID -- USER_ID
		);

-- BOOKMARK
ALTER TABLE BOOKMARK
	ADD CONSTRAINT FK_USERS_TO_BOOKMARK -- USERS -> BOOKMARK
		FOREIGN KEY (
			USER_ID -- USER_ID
		)
		REFERENCES USERS ( -- USERS
			USER_ID -- USER_ID
		);
		
INSERT INTO USERS_AUTH VALUES(1, 'ADMIN');

INSERT INTO USERS_AUTH VALUES(2, 'USER');

INSERT INTO USERS(USER_ID, USER_PW, USER_NAME, AUTH_CODE, BIRTH, EMAIL, TEL, DELFLAG)
	VALUES('qkrekfthsus', '$2a$12$sZqGS4fcfQtpPl3VuLUjA.lfTprHe9kMlcJPXz2j.Z4VPs/0xq4em', '이종표',
	1, '1997-05-13', 'qkrekfthsus@naver.com',
	'010-1234-4567', 'N');
	

INSERT INTO ADMIN.USERS
(USER_ID, USER_PW, USER_NAME, AUTH_CODE, BIRTH, EMAIL, TEL, DELFLAG)
VALUES('aaaa', '$2a$12$ri3pTBlMAOIilwZGmg4gF.bdYP02iLYRYJWWLvWVnTtMpCQ/4fSkG',
'aaaa', 2, SYSDATE, 'aaaa@aaaa.com', '010-1234-5678', 'N');

INSERT INTO ADMIN.USERS
(USER_ID, USER_PW, USER_NAME, AUTH_CODE, BIRTH, EMAIL, TEL, DELFLAG)
VALUES('bbbb', '$2a$12$M5szXyjKn4HPhxJzjN.gu.VR6L8dIrxMNTbr49K.dUYy5tQauapBm',
'bbbb', 2, SYSDATE, 'bbbb@bbbb.com', '010-4321-9876', 'N');

INSERT INTO ADMIN.USERS
(USER_ID, USER_PW, USER_NAME, AUTH_CODE, BIRTH, EMAIL, TEL, DELFLAG)
VALUES('user01', '$2a$12$J3hl72pVcbSTlfXlJmtFseCzTmOMf0Nu/tS00REGUsZ26lI0FQ0CW',
'user01', 2, '1990-01-01', 'user01@naver.com', '010-4381-4281', 'N');

INSERT INTO ADMIN.USERS
(USER_ID, USER_PW, USER_NAME, AUTH_CODE, BIRTH, EMAIL, TEL, DELFLAG)
VALUES('user02', '$2a$12$akPtofYNPYBzyWKs/GFaHu9QFWz/tVQG9asTG.rZHlUkM4iwRlgam',
'user02', 2, '1997-05-12', 'user02@naver.com', '010-8851-4288', 'N');

INSERT INTO ADMIN.USERS
(USER_ID, USER_PW, USER_NAME, AUTH_CODE, BIRTH, EMAIL, TEL, DELFLAG)
VALUES('qwer', '$2a$12$ct9SdjoA3UvClQmdd77aRu.HKV2bFf8yCSqyAPiIHC2eVMASdCcPW',
'qwer', 2, '2000-11-15', 'qwer@qwer.com', '010-4568-7864', 'N');

INSERT INTO ADMIN.USERS
(USER_ID, USER_PW, USER_NAME, AUTH_CODE, BIRTH, EMAIL, TEL, DELFLAG)
VALUES('asdf', '$2a$12$w/9hV8hJ2ZsqeBGCgTv90uT1/nbRCaw0AU4UycSsfoyMuBmXe7Xky',
'asdf', 2, '2001-08-13', 'asdf@asdf.com', '010-7468-1354', 'N');

INSERT INTO ADMIN.USERS
(USER_ID, USER_PW, USER_NAME, AUTH_CODE, BIRTH, EMAIL, TEL, DELFLAG)
VALUES('zxcv', '$2a$12$Nu1Ie/gqLz6TE8FwXAPHl.idbRz3NEQRs.leCE7MIkHEYMSRU8iWe',
'zxcv', 2, SYSDATE, 'zxcv@zxcv.com', '010-7513-4215', 'N');

INSERT INTO ADMIN.USERS
(USER_ID, USER_PW, USER_NAME, AUTH_CODE, BIRTH, EMAIL, TEL, DELFLAG)
VALUES('abcd', '$2a$12$bHPFV697zOtj6A4Y8yP.7Om1FmxG4EyhOUmx5hwGWVqud2Io8Svr2',
'abcd', 2, '2005-12-08', 'abcd@abcd.com', '010-7866-4113', 'N');

INSERT INTO ADMIN.USERS
(USER_ID, USER_PW, USER_NAME, AUTH_CODE, BIRTH, EMAIL, TEL, DELFLAG)
VALUES('cccc', '$2a$12$HAde7Rkf//1FIf3181Tj.e5AFrn2BpK4izbUNwvLXamznAj1DtMv6',
'cccc', 2, SYSDATE, 'cccc@cccc.com', '010-7216-4646', 'N');

INSERT INTO ADMIN.USERS
(USER_ID, USER_PW, USER_NAME, AUTH_CODE, BIRTH, EMAIL, TEL, DELFLAG)
VALUES('admin01', '$2a$12$jnMeeeYstOKnzEdRQ4R19elsWQebPDvwQPWJ2bf0f6BHgj/ZnlU56',
'admin01', 1, '1995-08-15', 'admin01@admin.com', '010-5467-4541', 'N');

DELETE FROM USERS u WHERE USER_ID = 'abcd1234';
