SELECT POST_ID, MOZZLE_ID, USER_ID, TITLE, CONTENT, REFER, STEP, "DEPTH", REGDATE
FROM MOZZLE_POST
WHERE MOZZLE_ID = '1' AND USER_ID='reuser05';

SELECT * FROM MOZZLE m ;

INSERT INTO ADMIN.NOTIFICATION
(NOTICE_ID, USER_ID, MOZZLE_ID, "TYPE", NOTICE_TIME, READ_CHECKED, DELFLAG)
VALUES(NOTIFICATION_SEQ.NEXTVAL, 'qkrekfthsus', 1, '가입',  SYSDATE, 'N', 'N');

SELECT n.NOTICE_ID, n.MOZZLE_ID, n."TYPE", n.READ_CHECKED, m.IMAGE_SAVED 
FROM NOTIFICATION n INNER JOIN MOZZLE m 
ON n.MOZZLE_ID = m.MOZZLE_ID 
WHERE n.USER_ID = 'qkrekfthsus' AND n.DELFLAG ='N'
ORDER BY n.NOTICE_TIME DESC;
