--일정리스트
SELECT S.SCHEDULE_ID,S.WRITER,S.TITLE,S.CONTENT,
		S.SCHEDULE_DATE ,S.REGDATE, si.LOCATION_NAME, si.ADDRESS, si.ADDRESS2, si.PHONE
		FROM SCHEDULES S
		INNER JOIN SCHEDULE_INFO si
		ON S.LOCATION_CODE = si.LOCATION_CODE;
--일정등록
INSERT INTO SCHEDULE_INFO
	(LOCATION_CODE ,LOCATION_NAME ,ADDRESS ,ADDRESS2 ,PHONE ,LOGUI ,LAT)
	VALUES(SCHEDULE_INFO_SEQ.NEXTVAL,'경기도','주소1','주소2','010-1111-1111',37.567896,126.9786567);
INSERT INTO SCHEDULE_INFO
	(LOCATION_CODE ,LOCATION_NAME ,ADDRESS ,ADDRESS2 ,PHONE ,LOGUI ,LAT)
	VALUES(SCHEDULE_INFO_SEQ.NEXTVAL,'부천시','주소1','주소2','010-2222-2222',37.567896,126.9786567);
INSERT INTO SCHEDULE_INFO
	(LOCATION_CODE ,LOCATION_NAME ,ADDRESS ,ADDRESS2 ,PHONE ,LOGUI ,LAT)
	VALUES(SCHEDULE_INFO_SEQ.NEXTVAL,'수원시','주소1','주소2','010-3333-3333',37.567896,126.9786567);
INSERT INTO SCHEDULE_INFO
	(LOCATION_CODE ,LOCATION_NAME ,ADDRESS ,ADDRESS2 ,PHONE ,LOGUI ,LAT)
	VALUES(SCHEDULE_INFO_SEQ.NEXTVAL,'서울','주소1','주소2','010-9999-9999',37.567896,126.9786567);
INSERT INTO SCHEDULE_INFO
	(LOCATION_CODE ,LOCATION_NAME ,ADDRESS ,ADDRESS2 ,PHONE ,LOGUI ,LAT)
	VALUES(SCHEDULE_INFO_SEQ.NEXTVAL,'인천','주소1','주소2','010-6666-6666',37.567896,126.9786567);
INSERT INTO SCHEDULE_INFO
	(LOCATION_CODE ,LOCATION_NAME ,ADDRESS ,ADDRESS2 ,PHONE ,LOGUI ,LAT)
	VALUES(SCHEDULE_INFO_SEQ.NEXTVAL,'제주도','주소1','주소2','010-1207-1207',37.567896,126.9786567);

-- 여기서부터는 SCHEDULES 
INSERT INTO SCHEDULES
	(SCHEDULE_ID, MOZZLE_ID, WRITER, TITLE, CONTENT, SCHEDULE_DATE, REGDATE, DELFLAG, LOCATION_CODE)
	VALUES(SCHEDULE_SEQ.NEXTVAL, 1 , '작성자1', 'TITLE1', 'CONTENT1', '2021-12-17', SYSDATE, 'N', 21);
INSERT INTO SCHEDULES
	(SCHEDULE_ID, MOZZLE_ID, WRITER, TITLE, CONTENT, SCHEDULE_DATE, REGDATE, DELFLAG, LOCATION_CODE)
	VALUES(SCHEDULE_SEQ.NEXTVAL, 1 , '작성자2', 'TITLE2', 'CONTENT2', '2021-12-17', SYSDATE, 'N', 22);
INSERT INTO SCHEDULES
	(SCHEDULE_ID, MOZZLE_ID, WRITER, TITLE, CONTENT, SCHEDULE_DATE, REGDATE, DELFLAG, LOCATION_CODE)
	VALUES(SCHEDULE_SEQ.NEXTVAL, 1 , '작성자3', 'TITLE3', 'CONTENT3', '2021-12-17', SYSDATE, 'N', 23);
INSERT INTO SCHEDULES
	(SCHEDULE_ID, MOZZLE_ID, WRITER, TITLE, CONTENT, SCHEDULE_DATE, REGDATE, DELFLAG, LOCATION_CODE)
	VALUES(SCHEDULE_SEQ.NEXTVAL, 1 , '작성자4', 'TITLE4', 'CONTENT4', '2021-12-17', SYSDATE, 'N', 24);
INSERT INTO SCHEDULES
	(SCHEDULE_ID, MOZZLE_ID, WRITER, TITLE, CONTENT, SCHEDULE_DATE, REGDATE, DELFLAG, LOCATION_CODE)
	VALUES(SCHEDULE_SEQ.NEXTVAL, 1 , '작성자5', 'TITLE5', 'CONTENT5', '2021-12-17', SYSDATE, 'N', 25);
INSERT INTO SCHEDULES
	(SCHEDULE_ID, MOZZLE_ID, WRITER, TITLE, CONTENT, SCHEDULE_DATE, REGDATE, DELFLAG, LOCATION_CODE)
	VALUES(SCHEDULE_SEQ.NEXTVAL, 1 , '작성자6', 'TITLE6', 'CONTENT6', '2021-12-17', SYSDATE, 'N', 26);


CREATE SEQUENCE SCHEDULE_SEQ;

SELECT * FROM SCHEDULE_INFO;
SELECT * FROM SCHEDULES s ;

--일정개수
SELECT NVL(COUNT(*),0)
FROM SCHEDULES
WHERE SCHEDULE_DATE = '2021-12-17';

--일정리스트 ?개만 출력 수정필요
SELECT SCHEDULES_ID,WRITER,TITLE,CONTENT,
SCHEDULES_DATE,REGDATE FROM (SELECT ROW_NUMBER() OVER(PARTITION BY SUBSTR(SHCEDULE_DATE,1,8) OREDER BY SCHEDULE_DATE RN, SCHEDULES_ID,WRITER,TITLE,CONTENT,
SCHEDULES_DATE,REGDATE 
FROM SCHEDULES
WHERE ID=#{schedule_id} AND SUBSTR(SCHEDULE_DATE,1,8)=#{yyyymmdd})
WHERE RN BETWEEN 1 AND 3;

--일정 상세
SELECT S.SCHEDULE_ID,S.WRITER,S.TITLE,S.CONTENT,
		S.SCHEDULE_DATE ,S.REGDATE, si.LOCATION_NAME, si.ADDRESS, si.ADDRESS2, si.PHONE
		FROM SCHEDULES S
		INNER JOIN SCHEDULE_INFO si
		ON S.LOCATION_CODE = si.LOCATION_CODE
		WHERE SCHEDULE_ID = 6;

SELECT * FROM SCHEDULES s ;

--일정변경
UPDATE SCHEDULES
SET TITLE='변경된TITLE',CONTENT='변경된CONTENT',SCHEDULE_DATE='2021-12-19'
WHERE SCHEDULE_ID = 2;

--일정삭제(delete)
  DELETE FROM SCHEDULES
   WHERE SCHEDULE_ID = 4;
   

  
  